### ISSUE TITLE
Add how to include many to many

### ISSUE THREAD

**Issue by lhotwll217** [learn-co-curriculum/phase-4-serializing-associations#2]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/4215/assignments/139529?module_item_id=289318

## What should be changed?

It would be nice if you guys included how to to a many-to-many association, especially since that syntax doesn't include the has_many , through: and instead just uses a has_many and leaves the associating up to the model. It's the least conventional thing in Rails so far IMO and important, obviously. It was used in a mock code challenge that was not the best time to learn it. 

## Additional context

> Add any other context about the problem here.

**Comment by lizbur10** [comment]
Hi @lhotwll217 ! Thank you for bringing this to our attention! The lesson has been updated to cover many-to-many associations. Please note that the update may not be reflected in your Canvas course, but it will be available to students moving forward.

Thanks for contributing to the Flatiron School curriculum 💙

**Comment by lhotwll217** [comment]
Thanks for letting me know! You rock.

Luke
